version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pdfs:/app/pdfs
    environment:
      - PDF_FOLDER_PATH=/app/pdfs
      - API_PORT=8000
      - API_HOST=0.0.0.0
    restart: unless-stopped
